[2022-04-28 21:40:33,742] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: qqqq.execute scheduled__2022-04-26T00:00:00+00:00 [queued]>
[2022-04-28 21:40:33,750] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: qqqq.execute scheduled__2022-04-26T00:00:00+00:00 [queued]>
[2022-04-28 21:40:33,750] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 21:40:33,751] {taskinstance.py:1244} INFO - Starting attempt 3 of 3
[2022-04-28 21:40:33,751] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 21:40:33,759] {taskinstance.py:1264} INFO - Executing <Task(SparkPedroOperator): execute> on 2022-04-26 00:00:00+00:00
[2022-04-28 21:40:33,764] {standard_task_runner.py:52} INFO - Started process 26 to run task
[2022-04-28 21:40:33,767] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'qqqq', 'execute', 'scheduled__2022-04-26T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/sp_rodaporfavor.py', '--cfg-path', '/tmp/tmp0w_p3yvv', '--error-file', '/tmp/tmpmh7rlxum']
[2022-04-28 21:40:33,768] {standard_task_runner.py:77} INFO - Job 6: Subtask execute
[2022-04-28 21:40:33,837] {logging_mixin.py:109} INFO - Running <TaskInstance: qqqq.execute scheduled__2022-04-26T00:00:00+00:00 [running]> on host qqqqexecute.bc601d1b1ed74c699b48a848d341beee
[2022-04-28 21:40:33,950] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=qqqq
AIRFLOW_CTX_TASK_ID=execute
AIRFLOW_CTX_EXECUTION_DATE=2022-04-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-26T00:00:00+00:00
[2022-04-28 21:40:33,951] {logging_mixin.py:109} INFO - opa
[2022-04-28 21:40:33,952] {sp_rodaporfavor.py:55} INFO - Creating sparkApplication
[2022-04-28 21:40:33,952] {logging_mixin.py:109} INFO - eae
[2022-04-28 21:40:33,952] {logging_mixin.py:109} INFO - hmm
[2022-04-28 21:40:33,992] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 209, in create_custom_object
    group=group, version=version, namespace=namespace, plural=plural, body=body
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api/custom_objects_api.py", line 183, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api/custom_objects_api.py", line 289, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 388, in request
    body=body)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 278, in POST
    body=body)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '76c163cc-7514-44fd-b3cd-d6bb8747c767', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '7b7487d6-037b-49b9-9752-32250e588612', 'X-Kubernetes-Pf-Prioritylevel-Uid': '50ee794a-350e-4c76-a37f-6f06a352ff2b', 'Date': 'Thu, 28 Apr 2022 21:40:33 GMT', 'Content-Length': '1022'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"SparkApplication.sparkoperator.k8s.io \"job-pi-{{ execution_date }}\" is invalid: metadata.name: Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"job-pi-{{ execution_date }}","group":"sparkoperator.k8s.io","kind":"SparkApplication","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}]},"code":422}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/dags/sp_rodaporfavor.py", line 64, in execute
    namespace=self.namespace,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 214, in create_custom_object
    raise AirflowException(f"Exception when calling -> create_custom_object: {e}\n")
airflow.exceptions.AirflowException: Exception when calling -> create_custom_object: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '76c163cc-7514-44fd-b3cd-d6bb8747c767', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '7b7487d6-037b-49b9-9752-32250e588612', 'X-Kubernetes-Pf-Prioritylevel-Uid': '50ee794a-350e-4c76-a37f-6f06a352ff2b', 'Date': 'Thu, 28 Apr 2022 21:40:33 GMT', 'Content-Length': '1022'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"SparkApplication.sparkoperator.k8s.io \"job-pi-{{ execution_date }}\" is invalid: metadata.name: Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"job-pi-{{ execution_date }}","group":"sparkoperator.k8s.io","kind":"SparkApplication","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}]},"code":422}



[2022-04-28 21:40:34,008] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=qqqq, task_id=execute, execution_date=20220426T000000, start_date=20220428T214033, end_date=20220428T214034
[2022-04-28 21:40:34,023] {standard_task_runner.py:92} ERROR - Failed to execute job 6 for task execute
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 209, in create_custom_object
    group=group, version=version, namespace=namespace, plural=plural, body=body
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api/custom_objects_api.py", line 183, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)  # noqa: E501
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api/custom_objects_api.py", line 289, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 345, in call_api
    _preload_content, _request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 176, in __call_api
    _request_timeout=_request_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 388, in request
    body=body)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 278, in POST
    body=body)
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '76c163cc-7514-44fd-b3cd-d6bb8747c767', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '7b7487d6-037b-49b9-9752-32250e588612', 'X-Kubernetes-Pf-Prioritylevel-Uid': '50ee794a-350e-4c76-a37f-6f06a352ff2b', 'Date': 'Thu, 28 Apr 2022 21:40:33 GMT', 'Content-Length': '1022'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"SparkApplication.sparkoperator.k8s.io \"job-pi-{{ execution_date }}\" is invalid: metadata.name: Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"job-pi-{{ execution_date }}","group":"sparkoperator.k8s.io","kind":"SparkApplication","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}]},"code":422}



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/airflow/dags/sp_rodaporfavor.py", line 64, in execute
    namespace=self.namespace,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 214, in create_custom_object
    raise AirflowException(f"Exception when calling -> create_custom_object: {e}\n")
airflow.exceptions.AirflowException: Exception when calling -> create_custom_object: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '76c163cc-7514-44fd-b3cd-d6bb8747c767', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '7b7487d6-037b-49b9-9752-32250e588612', 'X-Kubernetes-Pf-Prioritylevel-Uid': '50ee794a-350e-4c76-a37f-6f06a352ff2b', 'Date': 'Thu, 28 Apr 2022 21:40:33 GMT', 'Content-Length': '1022'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"SparkApplication.sparkoperator.k8s.io \"job-pi-{{ execution_date }}\" is invalid: metadata.name: Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","reason":"Invalid","details":{"name":"job-pi-{{ execution_date }}","group":"sparkoperator.k8s.io","kind":"SparkApplication","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"job-pi-{{ execution_date }}\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}]},"code":422}



[2022-04-28 21:40:34,063] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 21:40:34,193] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
