[2022-04-28 21:45:37,132] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: qqqq.monitor scheduled__2022-04-26T00:00:00+00:00 [queued]>
[2022-04-28 21:45:37,146] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: qqqq.monitor scheduled__2022-04-26T00:00:00+00:00 [queued]>
[2022-04-28 21:45:37,146] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 21:45:37,147] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-04-28 21:45:37,147] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 21:45:37,166] {taskinstance.py:1264} INFO - Executing <Task(SparkKubernetesSensor): monitor> on 2022-04-26 00:00:00+00:00
[2022-04-28 21:45:37,173] {standard_task_runner.py:52} INFO - Started process 27 to run task
[2022-04-28 21:45:37,178] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'qqqq', 'monitor', 'scheduled__2022-04-26T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/sp_rodaporfavor.py', '--cfg-path', '/tmp/tmpxg1mu8y9', '--error-file', '/tmp/tmpsz1sa2mk']
[2022-04-28 21:45:37,179] {standard_task_runner.py:77} INFO - Job 8: Subtask monitor
[2022-04-28 21:45:37,254] {logging_mixin.py:109} INFO - Running <TaskInstance: qqqq.monitor scheduled__2022-04-26T00:00:00+00:00 [running]> on host qqqqmonitor.f7db0adecfcc43ab85facd737571a86c
[2022-04-28 21:45:38,378] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=qqqq
AIRFLOW_CTX_TASK_ID=monitor
AIRFLOW_CTX_EXECUTION_DATE=2022-04-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-26T00:00:00+00:00
[2022-04-28 21:45:38,380] {spark_kubernetes.py:98} INFO - Poking: job-pi-21-45-24
[2022-04-28 21:45:38,433] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 236, in execute
    while not self.poke(context):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/sensors/spark_kubernetes.py", line 113, in poke
    raise AirflowException(f"Spark application failed with state: {application_state}")
airflow.exceptions.AirflowException: Spark application failed with state: FAILED
[2022-04-28 21:45:38,443] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=qqqq, task_id=monitor, execution_date=20220426T000000, start_date=20220428T214537, end_date=20220428T214538
[2022-04-28 21:45:38,471] {standard_task_runner.py:92} ERROR - Failed to execute job 8 for task monitor
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 236, in execute
    while not self.poke(context):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/sensors/spark_kubernetes.py", line 113, in poke
    raise AirflowException(f"Spark application failed with state: {application_state}")
airflow.exceptions.AirflowException: Spark application failed with state: FAILED
[2022-04-28 21:45:38,498] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 21:45:38,545] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
