[2022-04-28 21:51:34,929] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: qqqq.monitor scheduled__2022-04-26T00:00:00+00:00 [queued]>
[2022-04-28 21:51:34,940] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: qqqq.monitor scheduled__2022-04-26T00:00:00+00:00 [queued]>
[2022-04-28 21:51:34,940] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 21:51:34,941] {taskinstance.py:1244} INFO - Starting attempt 3 of 3
[2022-04-28 21:51:34,941] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 21:51:34,952] {taskinstance.py:1264} INFO - Executing <Task(SparkKubernetesSensor): monitor> on 2022-04-26 00:00:00+00:00
[2022-04-28 21:51:34,958] {standard_task_runner.py:52} INFO - Started process 26 to run task
[2022-04-28 21:51:34,961] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'qqqq', 'monitor', 'scheduled__2022-04-26T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/sp_rodaporfavor.py', '--cfg-path', '/tmp/tmp80o8znnu', '--error-file', '/tmp/tmpmzub2bw7']
[2022-04-28 21:51:34,962] {standard_task_runner.py:77} INFO - Job 12: Subtask monitor
[2022-04-28 21:51:35,026] {logging_mixin.py:109} INFO - Running <TaskInstance: qqqq.monitor scheduled__2022-04-26T00:00:00+00:00 [running]> on host qqqqmonitor.f535162ca8944712b1a703984ba5927d
[2022-04-28 21:51:35,138] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=qqqq
AIRFLOW_CTX_TASK_ID=monitor
AIRFLOW_CTX_EXECUTION_DATE=2022-04-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-26T00:00:00+00:00
[2022-04-28 21:51:35,138] {spark_kubernetes.py:98} INFO - Poking: job-pi-21-51-21
[2022-04-28 21:51:35,173] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 236, in execute
    while not self.poke(context):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/sensors/spark_kubernetes.py", line 113, in poke
    raise AirflowException(f"Spark application failed with state: {application_state}")
airflow.exceptions.AirflowException: Spark application failed with state: FAILED
[2022-04-28 21:51:35,182] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=qqqq, task_id=monitor, execution_date=20220426T000000, start_date=20220428T215134, end_date=20220428T215135
[2022-04-28 21:51:35,195] {standard_task_runner.py:92} ERROR - Failed to execute job 12 for task monitor
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 236, in execute
    while not self.poke(context):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/sensors/spark_kubernetes.py", line 113, in poke
    raise AirflowException(f"Spark application failed with state: {application_state}")
airflow.exceptions.AirflowException: Spark application failed with state: FAILED
[2022-04-28 21:51:35,216] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 21:51:35,248] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
